version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu

#version: 0.0
#os: linux
#
#files:
#  - source:  /
#    destination: /home/ubuntu/spring-github-action
#    overwrite: yes
#
#permissions:
#  - object: /
#    owner: ubuntu
#    group: ubuntu
#
#hooks:
#  AfterInstall:
#    - location: scripts/stop.sh
#      timeout: 60
#  ApplicationStart:
#    - location: scripts/start.sh
#      timeout: 60
